apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: observai-query-backend
  namespace: testing-workspace
  labels:
      app.kubernetes.io/part-of: observai
spec:
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - observai-query-backend
        from:
          kind: ImageStreamTag
          namespace: testing-workspace
          name: 'observai-query-backend:latest'
  replicas: 1
  selector:
      app: observai-query-backend
  template:
    metadata:
      labels:
        app: observai-query-backend
    spec:
      containers:
        - name: observai-query-backend
          image: >-
            image-registry.openshift-image-registry.svc:5000/testing-workspace/observai-query-backend
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: observai-query-backend-config
                  key: APP_PORT
            - name: APP_HOST
              valueFrom:
                configMapKeyRef:
                  name: observai-query-backend-config
                  key: APP_HOST
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: observai-query-backend-config
                  key: MONGODB_URL                                
          imagePullPolicy: IfNotPresent
      restartPolicy: Always




